# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

mode: production

image:
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

mcc: "001"
mnc: "01"
msin: "0000000001"

amf:
  ip: "192.168.1.1"

key: "465B5CE8B199B49FAA5F0A2EE238A6BC"
op: "E8ED289DEBA952E4283B54E88E6183CA"